apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: pcs
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: pcs
        tier: backend
    spec:
      containers:
        - name: pcs
          image: robotnikdev/plant-care-system:backend-latest
          ports:
            - protocol: TCP
              containerPort: 9000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: pcs
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
