apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    pid /var/run/nginx.pid;
    
    events {
        worker_connections 1024;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
    
        server {
            listen 80;
            server_name localhost;
            root /usr/share/nginx/html;
            index index.html;
    
            location / {
                try_files $uri $uri/ =404;
            }
        }
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: pcs
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: pcs
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: robotnikdev/plant-care-system:frontend-latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: pcs
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
