[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["serde_json", "json"] }
wasm-bindgen-futures = "0.4.50"
shared = { path = "../shared" }
